//
// Generated by JavaToPas v1.4 20140515 - 180918
/// /////////////////////////////////////////////////////////////////////////////
unit AndroidSDK.IntentService;

interface

uses
  AndroidAPI.JNIBridge,
  AndroidAPI.JNI.JavaTypes,
  AndroidAPI.JNI.GraphicsContentViewText;

type
  JIntentService = interface;

  JIntentServiceClass = interface(JObjectClass)
    ['{9C4C015B-A1BC-47C1-AA32-1BE34DCC4095}']
    function init(&name: JString): JIntentService; cdecl; // (Ljava/lang/String;)V A: $1
    function onStartCommand(intent: JIntent; flags: Integer; startId: Integer): Integer; cdecl;
    // (Landroid/content/Intent;II)I A: $1
    procedure onCreate; cdecl; // ()V A: $1
    procedure onDestroy; cdecl; // ()V A: $1
    procedure onStart(intent: JIntent; startId: Integer); cdecl; // (Landroid/content/Intent;I)V A: $1
    procedure setIntentRedelivery(enabled: boolean); cdecl; // (Z)V A: $1
  end;

  [JavaSignature('android/app/IntentService')]
  JIntentService = interface(JObject)
    ['{FDC7122E-D75B-4133-81CD-62108435BD51}']
    function onStartCommand(intent: JIntent; flags: Integer; startId: Integer): Integer; cdecl;
    // (Landroid/content/Intent;II)I A: $1
    procedure onCreate; cdecl; // ()V A: $1
    procedure onDestroy; cdecl; // ()V A: $1
    procedure onStart(intent: JIntent; startId: Integer); cdecl; // (Landroid/content/Intent;I)V A: $1
    procedure setIntentRedelivery(enabled: boolean); cdecl; // (Z)V A: $1
    procedure onHandleIntent(intent: JIntent); cdecl;
  end;

  TJIntentService = class(TJavaGenericImport<JIntentServiceClass, JIntentService>)
  end;

  MyIntentService = class(TJIntentService)
    procedure onHandleIntent(intent: JIntent); cdecl;
  end;

implementation

{ MyIntentService }

uses AndroidSDK.Toast;

procedure MyIntentService.onHandleIntent(intent: JIntent);
begin
  ShowToast('Sono nel servizio');
end;

end.
